import { randomBytes } from "node:crypto";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { DeleteObjectCommand, GetObjectCommand, NoSuchKey, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { decryptBytes, encryptBytes, encryptionConfigured, isEncryptedBytes } from "../lib/crypto.js";

/**
 * Where uploaded files (property photos, greeting audio) live. The database keeps only
 * the key and metadata; the bytes go to a directory on the server (development,
 * single-server installs) or an S3-compatible bucket (AWS S3, Cloudflare R2, MinIO…).
 *
 * Keys are generated by the server, never taken from the request. When
 * DATA_ENCRYPTION_KEY is set, files are encrypted (AES-256-GCM) before they leave the
 * process, so neither the disk nor the bucket holds readable audio or photos.
 */
export interface BlobStore {
  put(key: string, bytes: Buffer): Promise<void>;
  /** null when the file doesn't exist. */
  get(key: string): Promise<Buffer | null>;
  delete(key: string): Promise<void>;
}

const KEY_RE = /^[A-Za-z0-9_-]+(?:\/[A-Za-z0-9_-]+)*(?:\.[a-z0-9]{1,5})?$/;
export function assertKey(key: string) {
  if (!KEY_RE.test(key) || key.length > 300) throw new Error(`Invalid storage key: ${key}`);
}

/** A fresh key such as "brk_123/photos/9f2c…". */
export const newKey = (brokerageId: string, kind: string, ext = "") =>
  `${brokerageId.replace(/[^A-Za-z0-9_-]/g, "")}/${kind}/${randomBytes(16).toString("hex")}${ext}`;

export class LocalDiskStore implements BlobStore {
  constructor(private readonly root: string) {}

  private file(key: string) {
    assertKey(key);
    const full = path.resolve(this.root, key);
    if (!full.startsWith(path.resolve(this.root) + path.sep)) throw new Error("Invalid storage key");
    return full;
  }

  async put(key: string, bytes: Buffer) {
    const target = this.file(key);
    await mkdir(path.dirname(target), { recursive: true, mode: 0o700 });
    const tmp = `${target}.${randomBytes(6).toString("hex")}.tmp`;
    await writeFile(tmp, bytes, { mode: 0o600 });
    await rename(tmp, target);
  }

  async get(key: string) {
    try {
      return await readFile(this.file(key));
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
      throw err;
    }
  }

  async delete(key: string) {
    await rm(this.file(key), { force: true });
  }
}

export class S3Store implements BlobStore {
  private readonly client: S3Client;

  constructor(private readonly bucket: string, private readonly prefix = "") {
    this.client = new S3Client({
      region: process.env.S3_REGION ?? "auto",
      endpoint: process.env.S3_ENDPOINT || undefined,
      forcePathStyle: process.env.S3_FORCE_PATH_STYLE === "true",
      credentials:
        process.env.S3_ACCESS_KEY_ID && process.env.S3_SECRET_ACCESS_KEY
          ? { accessKeyId: process.env.S3_ACCESS_KEY_ID, secretAccessKey: process.env.S3_SECRET_ACCESS_KEY }
          : undefined, // falls back to the standard AWS credential chain (IAM role etc.)
    });
  }

  private k(key: string) {
    assertKey(key);
    return this.prefix + key;
  }

  async put(key: string, bytes: Buffer) {
    await this.client.send(new PutObjectCommand({ Bucket: this.bucket, Key: this.k(key), Body: bytes, ContentType: "application/octet-stream" }));
  }

  async get(key: string) {
    try {
      const res = await this.client.send(new GetObjectCommand({ Bucket: this.bucket, Key: this.k(key) }));
      return res.Body ? Buffer.from(await res.Body.transformToByteArray()) : null;
    } catch (err) {
      if (err instanceof NoSuchKey || (err as { name?: string }).name === "NoSuchKey") return null;
      throw err;
    }
  }

  async delete(key: string) {
    await this.client.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: this.k(key) }));
  }
}

/** Encrypts on the way in and decrypts on the way out when DATA_ENCRYPTION_KEY is set. */
export class EncryptingStore implements BlobStore {
  constructor(private readonly inner: BlobStore) {}
  put(key: string, bytes: Buffer) {
    return this.inner.put(key, encryptionConfigured() ? encryptBytes(bytes) : bytes);
  }
  async get(key: string) {
    const stored = await this.inner.get(key);
    return stored && isEncryptedBytes(stored) ? decryptBytes(stored) : stored;
  }
  delete(key: string) {
    return this.inner.delete(key);
  }
}

let store: BlobStore | undefined;
/** STORAGE_DRIVER=s3 (with S3_BUCKET) or local (STORAGE_DIR, default ./storage). */
export function getBlobStore(): BlobStore {
  if (!store) {
    const driver = process.env.STORAGE_DRIVER ?? "local";
    let base: BlobStore;
    if (driver === "s3") {
      const bucket = process.env.S3_BUCKET;
      if (!bucket) throw new Error("STORAGE_DRIVER=s3 needs S3_BUCKET");
      base = new S3Store(bucket, process.env.S3_PREFIX ?? "");
    } else if (driver === "local") {
      base = new LocalDiskStore(path.resolve(process.env.STORAGE_DIR ?? "storage"));
    } else {
      throw new Error(`Unknown STORAGE_DRIVER ${driver}`);
    }
    store = new EncryptingStore(base);
  }
  return store;
}
/** For tests. */
export const setBlobStore = (s: BlobStore | undefined) => {
  store = s;
};
